---
- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: restart postgresql
  become: yes
  service:
    name: postgresql
    state: restarted
    enabled: yes

- name: restart zabbix-server
  become: yes
  service:
    name: zabbix-server
    state: restarted
    enabled: yes

- name: restart php-fpm
  systemd:
    name: php8.1-fpm
    state: restarted
    enabled: yes
