---
- name: Setup Common Packages and Base Configuration
  hosts: all
  become: true
  roles:
    - common
    - zabbix-agent

- name: Setup Load Balancer Server
  hosts: load_balancers
  become: true
  vars:
    postgresql_master_host: "{{ hostvars['web01']['ansible_default_ipv4']['address'] }}"
    postgresql_replica_host: "{{ hostvars['web02']['ansible_default_ipv4']['address'] }}"
    zabbix_server_ip: "{{ hostvars['monitor01']['ansible_default_ipv4']['address'] }}"
  roles:
    - loadbalancer

- name: Setup Web and Database Master Server
  hosts: web_servers[0]
  become: true
  vars:
    postgresql_master_host: "{{ hostvars['web01']['ansible_default_ipv4']['address'] }}"
    postgresql_replica_host: "{{ hostvars['web02']['ansible_default_ipv4']['address'] }}"
    zabbix_server_ip: "{{ hostvars['monitor01']['ansible_default_ipv4']['address'] }}"
  roles:
    - webserver
    - database
    - mediawiki

- name: Setup Web and Database Replica Server
  hosts: web_servers[1]
  become: true
  vars:
    postgresql_master_host: "{{ hostvars['web01']['ansible_default_ipv4']['address'] }}"
    postgresql_replica_host: "{{ hostvars['web02']['ansible_default_ipv4']['address'] }}"
    zabbix_server_ip: "{{ hostvars['monitor01']['ansible_default_ipv4']['address'] }}"
  roles:
    - webserver
    - database
    - mediawiki

- name: Setup Monitoring, Backup and Restore Server
  hosts: monitoring_servers
  become: true
  vars:
    postgresql_master_host: "{{ hostvars['web01']['ansible_default_ipv4']['address'] }}"
    postgresql_replica_host: "{{ hostvars['web02']['ansible_default_ipv4']['address'] }}"
    zabbix_server_ip: "{{ hostvars['monitor01']['ansible_default_ipv4']['address'] }}"
  roles:
    - zabbix-server
    - backup-restore
