---
- name: Установить nginx (если не установлен)
  apt:
    name: nginx
    state: present
  become: yes

- name: Копировать конфигурацию loadbalancer nginx
  template:
    src: nginx-loadbalancer.conf.j2 
    dest: /etc/nginx/conf.d/loadbalancer.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  when: not ansible_check_mode

- name: Перезапустить nginx
  systemd:
    name: nginx
    state: restarted
  become: yes
  when: not ansible_check_mode

