---
- name: Настроить postgresql.conf для реплики
  template:
    src: postgresql.replica.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0644'
  notify: restart postgresql
  become: yes
  check_mode: no

- name: Настроить pg_hba.conf для реплики
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: '0640'
  notify: restart postgresql
  become: yes
  check_mode: no

- name: Остановить PostgreSQL перед инициализацией
  service:
    name: postgresql
    state: stopped

- name: Удалить старые данные кластера
  file:
    path: "/var/lib/postgresql/{{ postgresql_version }}/main"
    state: absent

- name: Сделать base backup с мастера
  shell: >
    PGPASSWORD={{ replication_password }} pg_basebackup -h {{ postgresql_master }}
    -D /var/lib/postgresql/{{ postgresql_version }}/main
    -U {{ replication_user }} -P -v -R
  become_user: postgres
  become: yes
  args:
    executable: /bin/bash
  check_mode: no

- name: Создать recovery.conf
  template:
    src: recovery.conf.j2
    dest: "/var/lib/postgresql/{{ postgresql_version }}/main/recovery.conf"
    owner: postgres
    group: postgres
    mode: '0644'
  notify: restart postgresql
  become: yes
  check_mode: no

- name: Запустить PostgreSQL
  service:
    name: postgresql
    state: started
  become: yes
  check_mode: no

